### ISSUE TITLE
Task - API data manipulation 

### ISSUE THREAD

**Issue by stevoo1999** [UB-CSE/course-project-a6-teamnosleep#26]
Data manipulation for directions pulled from the API so that the user can see their directions from the format we will be receiving from the API

Acceptance Test

1.We must be able to take data from the api and manipulate it in a standard way

2. UNderstand the format of the data given to us

**Comment by CaseyRDolan** [comment]
The following is the documentation I believe we will need for the above task, the link to the full documentation is https://developers.google.com/maps/documentation/javascript/directions. Please note that the documentation found at this link https://developers.google.com/maps/documentation/directions/overview may come up if you try googling the documentation yourself but should not be used. The first is how to use the direction api through the JavaScript map which is what we are interested in doing, the second is how to use the direction api as a standalone service with no map linked and thus very little use to use at this time

----------------------------------------------------------------------------------------------------------------------------------------------


To use directions in the Maps JavaScript API, create an object of type DirectionsService and call DirectionsService.route() to initiate a request to the Directions service, passing it a DirectionsRequest object literal containing the input terms and a callback method to execute upon receipt of the response.


The DirectionsRequest object literal contains the following fields:

{
  origin: LatLng | String | google.maps.Place,         
  destination: LatLng | String | google.maps.Place,
  travelMode: TravelMode,
  transitOptions: TransitOptions,
  drivingOptions: DrivingOptions,
  unitSystem: UnitSystem,
  waypoints[]: DirectionsWaypoint,
  optimizeWaypoints: Boolean,
  provideRouteAlternatives: Boolean,
  avoidFerries: Boolean,
  avoidHighways: Boolean,
  avoidTolls: Boolean,
  region: String
}

origin --- his value may be specified as a String (for example, "Chicago, IL") or use the place autocompelete feature used in this example https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-directions

destination --- same as origin 

travel mode  --- Driving, walking, etc

transit options --- Public transit options

driving options --- locked behind paywall
----------------------------------------------------------------------------------------------------------------------------------------------

Full documentation on rendering the result found here https://developers.google.com/maps/documentation/javascript/directions#RenderingDirections

Initiating a directions request to the DirectionsService with the route() method requires passing a callback which executes upon completion of the service request. This callback will return a DirectionsResult and a DirectionsStatus code in the response.

Displaying the DirectionsResult
The DirectionsResult contains the result of the directions query, which you may either handle yourself, or pass to a DirectionsRenderer object, which can automatically handle displaying the result on a map.

To display a DirectionsResult using a DirectionsRenderer, you need to do the following:

Create a DirectionsRenderer object.
Call setMap() on the renderer to bind it to the passed map.
Call setDirections() on the renderer, passing it the DirectionsResult as noted above. Because the renderer is an MVCObject, it will automatically detect any changes to its properties and update the map when its associated directions have changed.

-------------------------------------------------------------------------------------------------------------------------------------------------

The DirectionsResult Object

When sending a directions request to the DirectionsService, you receive a response consisting of a status code, and a result, which is a DirectionsResult object. The DirectionsResult is an object literal with the following fields:

geocoded_waypoints[] --- contains an array of DirectionsGeocodedWaypoint objects, each one containing details about the geocoding of origin, destination and waypoints.

routes[] --- contains an array of DirectionsLeg objects. Each route indicates a way to get from the origin to the destination provided in the DirectionsRequest. Generally, only one route is returned for any given request, unless the request's provideRouteAlternatives field is set to true, in which, multiple routes may be returned.

A DirectionsLeg defines a single leg of a journey from the origin to the destination in the calculated route. For routes that contain no waypoints, the route will consist of a single "leg," but for routes that define one or more waypoints, the route will consist of one or more legs, corresponding to the specific legs of the journey.

The Directionsleg object contains among other things the most atomic unit of the route, the direction step

A DirectionsStep is the most atomic unit of a direction's route, containing a single step describing a specific, single instruction on the journey. E.g. "Turn left at W. 4th St." The step not only describes the instruction but also contains distance and duration information relating to how this step relates to the following step. For example, a step denoted as "Merge onto I-80 West" may contain a duration of "37 miles" and "40 minutes," indicating that the next step is 37 miles/40 minutes from this 

NOTE --- waypoints limited to 25
