### ISSUE TITLE
As a travelling businessman, I want to input my location so I can find high class restaurants and locals to take out potential clients.  

### ISSUE THREAD

**Issue by stevoo1999** [UB-CSE/course-project-a6-teamnosleep#5]
Acceptance Tests:
1. Verify that location shows on application.
2. Verify that price range is enabled.
3. Verify that correct restaurant is selected

**Comment by mnshishk** [comment]
Edit: it would seem that the google maps api has this feature, however, it is not free. 

The team has looked into trying to solving this problem (during the week of nov 9) but proved to be quite painful in incorporation with google api (due to the difference of data needed).

As soon as approved, this user story can be counted as deprecated/impossible for current semester.
